# TODO: Check if these tasks can be run with xtask instead of docker-compose

services:
  lint:
    build: .
    command: just fmt check
    volumes:
      - .:/app
    profiles:
      - ci

  check:
    build: .
    command: just check
    volumes:
      - .:/app
    profiles:
      - ci

  build:
    build: .
    command: just build
    volumes:
      - .:/app
    profiles:
      - ci
