name: Check

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Code Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker compose build check

      - name: Run check
        run: |
          docker compose run check
