name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format:
    name: Code Formatting
    uses: ./.github/workflows/format.yml

  check:
    name: Code Check
    needs: format
    uses: ./.github/workflows/check.yml

  build:
    name: Build Release
    needs: check
    uses: ./.github/workflows/build.yml
