name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint Check
    uses: ./.github/workflows/lint.yml

  build:
    name: Build Check
    needs: lint
    uses: ./.github/workflows/build.yml
