name: Format

on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    name: Code Formatting Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker compose build lint
        working-directory: ./firmware

      - name: Run formatter check
        run: docker compose run lint
        working-directory: ./firmware
