name: Lint

on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    name: Format and Lint Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker compose build lint

      - name: Run formatter check
        run: |
          docker compose run lint
